services:
  mongo_db:
    image: mongo
    restart: always

  server:
    image: nodejs
    volumes:
      - .:/server
      - /server/node_modules
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://mongo_db:27017/mydb
      - FRONT_URL
    depends_on:
      - mongo_db
    command: node server.js
  mongo_seed:
    image: mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    command: mongoimport --host mongo_db --db mydb --collection users --type json --file /mongo-seed/init.json --jsonArray
